/**
 * Generates `src/symbols.ts` from the `scripts/symbols.html` reference document.
 *
 * The HTML is a flat list of `<li>` entries, one per Typst symbol, e.g.:
 *
 *   <li
 *     id="symbol-chevron.l"
 *     data-codex-name="chevron.l"
 *     data-latex-name="\langle"
 *     data-value="⟨"
 *     data-deprecation="`angle.l` is deprecated, use `chevron.l` instead"
 *     ...
 *   >
 *
 * We keep only entries that have a LaTeX name (those are the ones useful for
 * converting TeX to Typst) and emit them keyed by their Typst (codex) name. The
 * key is the Typst name, so it is not repeated inside each entry:
 *
 *   { 'chevron.l': { latex: '\\langle', value: '⟨' } }
 *
 * Run with: `bun run generate:symbols`
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

interface TexSymbol {
  latex: string;
  value: string;
  deprecated?: string;
}

const ENTITIES: Record<string, string> = {
  '&amp;': '&',
  '&lt;': '<',
  '&gt;': '>',
  '&quot;': '"',
  '&apos;': "'",
  '&nbsp;': '\u00a0',
};

function decodeEntities(value: string): string {
  return value.replace(/&(?:amp|lt|gt|quot|apos|nbsp);/g, (m) => ENTITIES[m] ?? m);
}

function attr(block: string, name: string): string | undefined {
  const match = block.match(new RegExp(`${name}="([^"]*)"`));
  return match ? decodeEntities(match[1]) : undefined;
}

function main() {
  const root = join(import.meta.dir, '..');
  const content = readFileSync(join(import.meta.dir, 'symbols.html'), 'utf-8');

  const blocks = content.match(/<li\b[\s\S]*?>/g) ?? [];
  const symbols: Record<string, TexSymbol> = {};
  let skipped = 0;

  for (const block of blocks) {
    const typst = attr(block, 'data-codex-name');
    const latex = attr(block, 'data-latex-name');
    const value = attr(block, 'data-value');
    const deprecated = attr(block, 'data-deprecation');

    // Only symbols with a LaTeX name are useful for TeX -> Typst conversion.
    if (!typst || !latex || value === undefined) {
      skipped += 1;
      continue;
    }

    symbols[typst] = { latex, value, ...(deprecated ? { deprecated } : {}) };
  }

  const entries = Object.entries(symbols).sort(([a], [b]) => a.localeCompare(b));

  const lines = entries.map(([id, sym]) => {
    const parts = [
      `latex: ${JSON.stringify(sym.latex)}`,
      `value: ${JSON.stringify(sym.value)}`,
    ];
    if (sym.deprecated) parts.push(`deprecated: ${JSON.stringify(sym.deprecated)}`);
    return `  ${JSON.stringify(id)}: { ${parts.join(', ')} },`;
  });

  const out = `// This file is generated by \`scripts/generate-symbols.ts\` from \`scripts/symbols.html\`.
// Do not edit by hand; run \`bun run generate:symbols\` to regenerate.

export interface TexSymbol {
  /** The LaTeX macro that produces this symbol, e.g. \`\\\\langle\`. */
  latex: string;
  /** The rendered Unicode value, e.g. \`⟨\`. */
  value: string;
  /** Present when the Typst name is deprecated; describes the replacement. */
  deprecated?: string;
}

/** Typst symbols keyed by their Typst (codex) name, e.g. \`chevron.l\`. */
export const symbols: Record<string, TexSymbol> = {
${lines.join('\n')}
};
`;

  writeFileSync(join(root, 'src', 'symbols.ts'), out);
  console.log(
    `Wrote ${entries.length} symbols to src/symbols.ts (skipped ${skipped} without a LaTeX name)`,
  );
}

main();
